#!/usr/bin/env python3
"""Regenerate the plotly figure embedded in docs/index.html.

The page itself is hand-written prose; only the block between the
``BEGIN PLOTLY FIGURE`` / ``END PLOTLY FIGURE`` markers is generated. The
figure comes from a saved plotly JSON rather than from the simulation, so
rebuilding the page never touches /orange and takes a fraction of a second:

    # in the notebook, once the figure looks right
    figure.write_json('../figures/bhof_occupation.json')

    # then, from the repo root
    python py_files/build_docs.py

The div id is pinned instead of letting plotly mint a fresh UUID each time,
so a rebuild that changes nothing produces no diff, and a rebuild that does
change something produces a diff you can actually read.
"""
import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BEGIN_MARKER = '<!-- BEGIN PLOTLY FIGURE'
END_MARKER = '<!-- END PLOTLY FIGURE -->'

# Matches the plate the page's CSS is written around; the figure is sized here
# rather than in the plotly layout so the page keeps the last word on layout.
WRAPPER_STYLE = 'height:660px; width:1080px;'

# Chrome we deliberately drop: the plotly logo, and the mode bar's own
# "download" that would hand out a differently-styled PNG.
PLOTLY_CONFIG = {'displaylogo': False, 'responsive': True}

# plotly.py points its <script> at cdn.plot.ly. That host loads fine on GitHub
# Pages but is not on the Claude Artifact content-security-policy allowlist, so
# the same page published there renders a blank plot with no error. jsdelivr
# serves byte-identical files for this package, so the Subresource Integrity
# hash plotly emits stays valid across the swap.
PLOTLY_VERSION = '4.0.0'
CDN_FROM = f'https://cdn.plot.ly/plotly-{PLOTLY_VERSION}.min.js'
CDN_TO = f'https://cdn.jsdelivr.net/npm/plotly.js-dist-min@{PLOTLY_VERSION}/plotly.min.js'


def use_portable_cdn(fragment):
    """Point the plotly <script> at a host both GitHub Pages and Artifacts allow."""
    if CDN_FROM not in fragment:
        raise SystemExit(
            f'Expected a {CDN_FROM} reference in the rendered fragment and found none. '
            f'If plotly was upgraded, update PLOTLY_VERSION (currently {PLOTLY_VERSION}).'
        )
    return fragment.replace(CDN_FROM, CDN_TO)


def render_fragment(figure_path, div_id):
    """Render a saved plotly figure as an embeddable HTML fragment.

    ``include_plotlyjs='cdn'`` keeps the page small (a self-contained embed is
    ~5 MB of bundled plotly.js); the CDN tag it emits is the one already in the
    page, so nothing about how the page loads changes.
    """
    import plotly.io as pio

    figure = pio.read_json(figure_path)
    return pio.to_html(
        figure,
        full_html=False,
        include_plotlyjs='cdn',
        div_id=div_id,
        config=PLOTLY_CONFIG,
    )


def splice(page_html, fragment):
    """Replace the marked block in ``page_html`` with a freshly wrapped fragment."""
    begin = page_html.find(BEGIN_MARKER)
    end = page_html.find(END_MARKER)
    if begin == -1 or end == -1:
        raise SystemExit(
            f'Could not find the {BEGIN_MARKER}...{END_MARKER} markers in the page. '
            'The generated block has to stay marked for this script to know what to replace.'
        )
    if end < begin:
        raise SystemExit('Found the END marker before the BEGIN marker; the page is malformed.')

    block = (
        f'{BEGIN_MARKER} - generated by py_files/build_docs.py, do not edit by hand -->\n'
        f'      <div style="{WRAPPER_STYLE}">{fragment}</div>\n'
        f'      {END_MARKER}'
    )
    return page_html[:begin] + block + page_html[end + len(END_MARKER):]


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--figure', type=Path,
                        default=REPO_ROOT / 'figures' / 'bhof_occupation.json',
                        help='plotly figure JSON written by fig.write_json (default: %(default)s)')
    parser.add_argument('--fragment', type=Path,
                        help='pre-rendered HTML fragment to embed instead of --figure; '
                             'an escape hatch for figures built outside the notebook')
    parser.add_argument('--page', type=Path, default=REPO_ROOT / 'docs' / 'index.html',
                        help='page to rewrite in place (default: %(default)s)')
    parser.add_argument('--div-id', default='bhof-occupation',
                        help='id of the plotly div (default: %(default)s)')
    arguments = parser.parse_args()

    if arguments.fragment is not None:
        fragment = arguments.fragment.read_text()
    else:
        if not arguments.figure.exists():
            raise SystemExit(
                f'No figure at {arguments.figure}. Save one from the notebook first:\n'
                f"    figure.write_json('{arguments.figure}')"
            )
        fragment = use_portable_cdn(render_fragment(arguments.figure, arguments.div_id))

    page_html = arguments.page.read_text()
    updated = splice(page_html, fragment.strip())
    if updated == page_html:
        print(f'{arguments.page}: figure unchanged')
        return
    arguments.page.write_text(updated)
    print(f'{arguments.page}: figure updated ({len(fragment):,} bytes embedded)')


if __name__ == '__main__':
    main()
